language: java

jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.9/typesafe-activator-1.3.9-minimal.zip
  - unzip -q typesafe-activator-1.3.9-minimal.zip
  - psql -c 'create database test;' -U postgres

script:
  - activator-1.3.9-minimal/bin/activator test

cache:
  directories:
    - $HOME/.ivy2/cache

before_cache:
 -  find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm