language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.6

services:
  - mongodb

before_script:
  - sleep 15

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache

before_cache:
 -  find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm