language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.6

services:
  - postgresql

before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-activator-1.3.6.zip
  - unzip -q typesafe-activator-1.3.6.zip
  - psql -c 'create database test;' -U postgres

script:
  - activator-dist-1.3.6/activator testOnly DatabaseTest

cache:
  directories:
    - $HOME/.ivy2/cache

before_cache:
 -  find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm